apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: mission-critical-pacman
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
